builds:
  - binary: cosmium
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: cosmium
    homepage: 'https://github.com/pikami/cosmium'
    repository:
      owner: pikami
      name: homebrew-brew
    commit_author:
      name: pikami
      email: git@pikami.org

dockers:
  - image_templates:
    - "ghcr.io/pikami/{{ .ProjectName }}:{{ .Version }}"
    - "ghcr.io/pikami/{{ .ProjectName }}:latest"
    dockerfile: Dockerfile
    use: docker
    build_flag_templates:
    - "--platform=linux/amd64"
    - "--pull"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.description=Lightweight Cosmos DB emulator"
    - "--label=org.opencontainers.image.url=https://github.com/pikami/cosmium"
    - "--label=org.opencontainers.image.source=https://github.com/pikami/cosmium"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"

checksum:
  name_template: 'checksums.txt'
